#Write a program to input eight numbers from the user and display all the unique numbers (once). 

s = set()
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)
n = int(input("Enter the number : "))
s.add(n)

print("Unique numbers are : ",s)
